{ "links" : [
		{
			"hockey": {
				"http://nhl.com": "nhl.com",
				"http://sports.yahoo.com/nhl/": "^yahoo",
				"http://sports.yahoo.com/nhl/scoreboard": "*scores",
				"http://hockey.fantasysports.yahoo.com/hockey": "fantasy",
				"http://lightning.nhl.com/": "tbl",
				"http://oilers.nhl.com/": "edm",
				"http://tsn.ca/nhl": "tsn.ca",
				"http://www.nicetimeonice.com/": "toi"
			},
			"baseball": {
				"http://mlb.mlb.com/": "mlb.com",
				"http://sports.yahoo.com/mlb": "^yahoo",
				"http://sports.yahoo.com/mlb/scoreboard": "*scores",
				"http://baseball.fantasysports.yahoo.com/b1": "fantasy",
				"http://m-abl.baseball.cbssports.com/": "^m-abl",
				"http://m-abl.baseball.cbssports.com/scoring/live": "*live",
				"http://www.baseballprospectus.com/": "bp",
				"http://www.mlb.com/mlb/fantasy/news/": "mlb fantasy",
				"http://mlbdepthcharts.com": "mlb depth",
				"http://www.fangraphs.com/": "fangraphs"
			},
			"football": {
				"http://www.nfl.com/news/around-the-league": "nfl greg",
				"https://gamerewind.nfl.com/nflgr/secure/schedule": "rewind",
				"http://sports.yahoo.com/nfl": "^yahoo",
				"http://sports.yahoo.com/nfl/scoreboard": "*scores",
				"http://football.fantasysports.yahoo.com/": "fantasy",
				"http://games.espn.go.com/ffl/leagueoffice?leagueId=723932&teamId=14&seasonId=2012": "espn",
				"http://www.footballoutsiders.com/": "fo",
				"http://www.grantland.com/": "grantland",
				"http://profootballtalk.nbcsports.com/": "pft",
				"http://www.profootballweekly.com/": "pfweek",
				"http://smartfootball.com/": "smart",
				"http://subscribers.footballguys.com/apps/news.php": "fguys",
				"http://sportsfrog.net": "sportsfrog",
				"http://sports.yahoo.com/college-football/": "^yahoo",
				"http://rivals.yahoo.com/ncaa/football/scoreboard": "*scores"
			},
			"google": {
				"https://gmail.google.com/": "^gmail",
				"https://mail.google.com/mail/u/0/h/": "*html email",
				"http://m.gmail.com/": "*mobile email",
				"https://google.com/": "search", 
				"https://plus.google.com/": "google +",
				"http://www.google.com/reader/": "reader",
				"https://www.google.com/voice/": "voice",
				"http://www.google.com/calendar/": "calendar",
				"http://docs.google.com/": "docs",
				"http://maps.google.com/": "maps",
				"http://www.google.com/analytics/": "analytics",
				"https://www.google.com/admanager/": "ad manager",
				"http://youtube.com/": "youtube",
				"http://picasaweb.google.com": "picasa",
				"http://translate.google.com/": "translate",
				"https://accounts.google.com/IssuedAuthSubTokens": "two factor",
				"https://www.google.com/a/cpanel/tnr.com/SetupWizard#CPanelHome": "apps dash",
	    		"https://www.google.com/dashboard/b/0/?hl=en-US&pli=1": "dash"
	    	},
	    	"digital": {
				"https://www.twitter.com/": "twitter",
				"https://twitter.com/#!/oiler/lists": "^lists",
				"https://twitter.com/#!/oiler/hockey": "**hockey list", 
				"https://twitter.com/#!/oiler/football": "**football list",
				"https://twitter.com/#!/oiler/baseball": "**baseball list",
				"https://twitter.com/#!/oiler/vegas": "**vegas list",
				"https://twitter.com/#!/oiler/favorites": "*favorites",
				"http://ssl.facebook.com/": "^facebook", 
				"http://m.facebook.com/": "*mobile fb",
				"http://about.me": "about.me",
				"http://www.instapaper.com/u": "instapaper",
				"http://bit.ly/": "bit.ly",
				"http://dropbox.com": "dropbox",
				"https://github.com/": "github",
				"https://foursquare.com/": "foursquare",
				"http://www.reddit.com/r/all/": "reddit",
				"http://oiler2.wordpress.com/wp-admin/": "wp",
				"https://www.formstack.com/admin/form/dashboard": "formstack",
				"https://console.aws.amazon.com/s3/home": "aws",
				"http://ifttt.com/dashboard": "ifttt",
				"http://getprismatic.com/newsfeed#": "prismatic",
				"http://oiler.phpfogapp.com": "thinkup",
				"http://hellofax.com": "hellofax",
				"http://www.trillian.im/chat": "trillian",
				"https://www.google.com/search?q=my+ip": "my ip"
			},
			"news": {
				"http://nytimes.com/": "nytimes",
				"http://www.wnyc.org/": "wnyc",
				"http://twit.tv/": "^twit", 
				"http://live.twit.tv/": "*live",
				"http://www.opensecrets.org/index.php": "opensecrets"
			},
			"stream": {
				"http://netflix.com/": "netflix",
				"http://pandora.com/": "pandora",
				"http://watch.slingbox.com/": "sling",
				"http://www.tnt.tv/video/?cid=61779": "tnt",
				"http://www.hulu.com/the-colbert-report": "colbert report",
				"http://www.hulu.com/the-daily-show-with-jon-stewart": "the daily show",
				"http://www.cbc.ca/sports/hockeynightincanada/video/": "hnic",
				"https://www.amazon.com/gp/video/library": "amazon",
				"http://hulu.com": "hulu",
				"http://hbogo.com": "hbogo",
				"http://www.cbsnews.com/sections/60minutes/main3415.shtml": "60 minutes"
			},
			"dev": {
				"http://screensiz.es/": "screensiz.es",
				"http://www.webpagetest.org/": "webpagetest",
				"http://code.google.com/speed/page-speed/docs/rules_intro.html": "page speed",
				"http://centralops.net/co/": "centralops",
				"http://validator.w3.org/": "W3C Validator",
				"http://www.nikmakris.com/images/blog/webding_characters.gif": "webdings",
				"http://www.pctools.com/guides/password/?length=24&phonetic=on&alpha=on&mixedcase=on&numeric=on&punctuation=on&nosimilar=on&quantity=9&generate=true#password_generator": "password gen",
				"http://html5boilerplate.com/": "html5 plate",
				"http://html5rocks.com/": "html5 rocks",
				"http://www.initializr.com/": "initalizer",
				"http://jsfiddle.net/": "jsfiddle",
				"http://jsonviewer.stack.hu/": "json viewer",
				"http://charactercounttool.com/": "char count",
				"http://jhy.io/tools/convert-word-to-plain-text": "word to text",
				"http://appinventor.mit.edu/": "app inventor",
				"http://javascript.crockford.com/": "d crockford"
			},
			"money": {
				"https://sunnet.suncoastfcu.org/": "ssfcu",
				"https://www.bankofamerica.com/index.jsp?page_msg=mbna": "mbna",
				"https://chaseonline.chase.com/": "chase"
			},
			"other": {
				"http://www.chelseapiers.com/sr/adult-hockey/schedules-standings.cfm": "chelseapiers",
				"http://www.chelseapiers.com/sportmgr/index.cfm?fuseaction=division.home&division_id=1702": "icedogs",
				"http://www.chelseapiers.com/sc/club/index.cfm": "club",
				"http://www.zogsports.com/nyc/Home.aspx": "zogsports",
				"http://randallsisland.org/wordpress/wp-content/uploads/2010/04/RI-Bronx-Shore-Existing-Fields-No-Orientation-signs.pdf": "zog map",
				"http://newyork.craigslist.org/mnh/": "ny craigslist",
				"http://tampa.craigslist.org/": "tb craigslist",
				"http://tv.yahoo.com/grid?lineup=us_DITV539&genres=&all=1&dur=&starttime=&starthour=&startdate=&.intl=us": "tv",
				"https://mail.yahoo.com": "yahoo",
				"http://mailinator.com/": "dodgeit",
				"http://www.indeed.com/": "indeed",
				"http://www.simplyhired.com/": "simplyhired",
				"http://jobs.wordpress.net/": "wp jobs",
				"http://dice.com/": "dice.com",
				"http://www.techmeme.com/events": "techmeme events",
				"http://newyork.craigslist.org/": "craigslist",
				"http://www.colbertnation.com/tickets": "colbert tix",
				"http://www.thedailyshow.com/tickets": "tds tix",
				"http://www.newyorkology.com/archives/calendar/index.php": "ny cal",
				"http://www.movietickets.com/house_detail.asp?house_id=7333": "bpc regal",
				"https://www.facebook.com/altnation/notes": "alt nation"
			},
			"shop": {
				"http://ebay.com/": "ebay",
				"http://amazon.com/": "amazon",
				"http://www.bestbuy.com/": "bestbuy",
				"http://slickdeals.net/": "slickdeals",
				"http://www.directv.com/": "directv",
				"http://www.verizon.com/myverizon": "myverizon",
				"http://www.attwireless.com/": "at&t",
				"http://tec.inetbiller.com/": "teco",
				"https://www22.verizon.com/myaccount/?ID=SignIn": "verizon",
				"http://www.sprint.com/personal/wireless/manage.html": "sprint",
				"http://www.stubhub.com/the-book-of-mormon-tickets/": "^mormon", 
				"http://newyork.craigslist.org/search/sss?query=book+of+mormon&srchType=A&minAsk=&maxAsk=": "**cl"
			},
			"side": [
				"tnr",
				"time",
				"mlb",
				"tbl",
				"nytrng",
				"dev",
				"twitter",
				"travel",
				"apt",
				"work",
				"matchup"
			]
		}
	]
}