{"links" : {
	"NHL": "",
	"yahoo": "http://sports.yahoo.com/nhl/scoreboard",
	"schedule": "http://forecaster.canada.com/faceoff/hockey/schedule.cgi",
	"tott": "http://forecaster.canada.com/faceoff/hockey/tott.cgi?TB",
	"goalie": "http://goaliepost.com/",
	"daily faceoff": "http://www2.dailyfaceoff.com/starting-goalies/",
	"team stats": "http://www.nhl.com/ice/teamstats.htm",
	"rink blog": "http://www.nhl.com/ice/blog.htm?id=219",
	"usa today": "http://sportsdirect.usatoday.com/matchups/nhl-matchups.aspx",
	"GEN": "",
	"BT forum": "http://www.bettingtalk.com/forum/forumdisplay.php/5-BettingTalk",
	"al": "http://www.bigal.com/Subscriptions/main.cfm",
	"beyond": "http://www.beyondthebets.com/",
	"fezzik": "http://lvasports.com/index.cfm",
	"lva boards": "http://www.lvasportsboards.com/",
	"covers": "http://www.covers.com/",
	"service plays": "http://forum.sbrforum.com/service-plays/",
	"rx service": "http://www.therxforum.com/forumdisplay.php?f=216",
	"a1 ncaaf": "http://a1serviceplays.com/forums/service-plays/ncaa-fb-service-plays/",
	"a1 nfl": "http://a1serviceplays.com/forums/service-plays/nfl-service-plays/",
	"a1 nhl": "http://a1serviceplays.com/forums/service-plays/nhl-service-plays/",
	"a1 mlb": "http://a1serviceplays.com/forums/service-plays/mlb-service-plays/",
	"wagerminds": "vwww.wagerminds.com",
	"database": "http://sportsdatabase.com/",
	"baseball info": "http://dailybaseballdata.com/cgi-bin/weather.pl",
	"insights": "http://www.sportsinsights.com/blog/",
	"betlabs": "http://www.sportsinsights.com/betlabs/dashboard.aspx",
	"NCAAF": "",
	"don best lines": "http://www.donbest.com/ncaaf/odds/",
	"matchups-cfb": "http://scores.covers.com/college-football-scores-matchups.aspx",
	"lines-cfb": "http://www.covers.com/odds/football/college-football-odds.aspx",
	"cfb picks": "http://www.handicapper.net/college-football-picks.php",
	"football post": "http://www.nationalfootballpost.com/sports-betting-analysis.html",
	"cfn": "http://cfn.scout.com/",
	"rivals": "http://www.rivals.com/",
	"ncaaf database": "http://stats.sportsbettingstats.com/Stats/Database/Football/NCAAF",
	"espn haney": "http://insider.espn.go.com/blog/travis-haney/",
	"espn steele": "http://search.espn.go.com/phil-steele/",
	"steele": "http://www.philsteele.com"
	}
}
