{"links" : {

	"GEN": "",
	"BT forum": "http://www.bettingtalk.com/forum/forumdisplay.php/5-BettingTalk",
	"al": "http://www.bigal.com/Subscriptions/main.cfm",
	"beyond": "http://www.beyondthebets.com/",
	"fezzik": "http://lvasports.com/index.cfm",
	"lva boards": "http://www.lvasportsboards.com/",
	"covers": "http://www.covers.com/",
	"service plays": "http://forum.sbrforum.com/service-plays/",
	"rx service": "http://www.therxforum.com/forumdisplay.php?f=216",
	"a1": "http://a1serviceplays.com/forums/service-plays/",
	"wagerminds": "vwww.wagerminds.com",
	"database": "http://sportsdatabase.com/",
	"insights": "http://www.sportsinsights.com/blog/",
	"betlabs": "http://www.sportsinsights.com/betlabs/dashboard.aspx",
	"book spy": "http://pregame.com/sportsbook_spy/default.aspx",

	"NHL": "",
	"yahoo": "http://sports.yahoo.com/nhl/scoreboard",
	"schedule": "http://forecaster.canada.com/faceoff/hockey/schedule.cgi",
	"tott": "http://forecaster.canada.com/faceoff/hockey/tott.cgi?TB",
	"goalie": "http://goaliepost.com/",
	"daily faceoff": "http://www2.dailyfaceoff.com/starting-goalies/",
	"team stats": "http://www.nhl.com/ice/teamstats.htm",
	"rink blog": "http://www.nhl.com/ice/blog.htm?id=219",
	"usa today": "http://sportsdirect.usatoday.com/matchups/nhl-matchups.aspx",

	"MLB": "",
	"ump main": "http://www.statfox.com/mlb/umpiremain.asp",
	"ump odds": "http://www.oddsshark.com/mlb/umpire-handicapping-statistics",
	"covers umps": "http://www.covers.com/pageLoader/pageLoader.aspx?page=/data/mlb/umpires/umpires.html",
	"ump crews": "https://twitter.com/UmpCrew/with_replies",
	"pitcher gbfb": "http://www.fangraphs.com/leaders.aspx?pos=all&stats=pit&lg=all&qual=y&type=2&season=2016&month=0&season1=2016&ind=0&team=0&rost=0&age=0&filter=&players=0&sort=4,a",
	"batter gbfb": "http://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=y&type=2&season=2016&month=0&season1=2016&ind=0&team=0&rost=0&age=0&filter=&players=0&sort=6,a", 
	"weather info": "http://dailybaseballdata.com/cgi-bin/weather.pl",

	"NCAAF": "",
	"don best lines": "http://www.donbest.com/ncaaf/odds/",
	"matchups-cfb": "http://scores.covers.com/college-football-scores-matchups.aspx",
	"lines-cfb": "http://www.covers.com/odds/football/college-football-odds.aspx",
	"cfb picks": "http://www.handicapper.net/college-football-picks.php",
	"football post": "http://www.nationalfootballpost.com/sports-betting-analysis.html",
	"cfn": "http://cfn.scout.com/",
	"rivals": "http://www.rivals.com/",
	"ncaaf database": "http://stats.sportsbettingstats.com/Stats/Database/Football/NCAAF",
	"espn haney": "http://insider.espn.go.com/blog/travis-haney/",
	"espn steele": "http://search.espn.go.com/phil-steele/",
	"steele": "http://www.philsteele.com"
	}
}
