{"links" : {
	"TIME WEB": "",
	"time": "http://www.time.com/time/",
	"newsfeed prod": "http://newsfeed.time.com/",
	"olym prod": "http://timeolympics.wordpress.com/",
	
	"ADMIN": "",
	"lightbox": "http://timethemoment.wordpress.com/wp-admin/",
	"newsfeed": "http://timenewsfeed.wordpress.com/wp-admin/index.php",
	"swampland": "http://timeswampland.wordpress.com/wp-admin/index.php",
	"wellness": "http://timewellness.wordpress.com/wp-admin/index.php",
	"thepage": "http://markhalperin.wordpress.com/wp-admin/",
	"keeping score": "http://timekeepingscore.wordpress.com/wp-admin/",
	"ideas": "http://timeopinions.wordpress.com/wp-admin/",
	"life": "http://timelifeblog.wordpress.com/wp-admin/",
	"ecocentris": "http://timeecocentric.wordpress.com/wp-admin/",
	"global spin": "http://timeglobalspin.wordpress.com/wp-admin/",
	"business": "http://timebusinessblog.wordpress.com/wp-admin/",
	"moneyland": "http://timecheapskate.wordpress.com/wp-admin/",
	"entertainment": "http://timeentertainment.wordpress.com/wp-admin/",
	"techland": "http://timenerdworld.wordpress.com/wp-admin/",
	"olympics": "http://timeolympics.wordpress.com/wp-admin",
	"work": "",
	"tt wifi": "http://mytime.timeinc.com/TT/telecom/wifi/ny1271?section=thingsToknow",
	"jira": "https://timedotcom.atlassian.net/",
	"basecamp": "https://timedotcom.basecamphq.com/",
	"bugzilla": "https://bugs.timeinc.net/index.cgi",
	"doc setup": "https://docs.google.com/document/d/1U6lbotME0OTEl1fgfRu9oD8iwC41-9Wa7cj8N2Kupdo/edit?pli=1",
	"doc mobile apps feed": "https://docs.google.com/spreadsheet/ccc?key=0Am2YSG_tU8HbdHpzYXFGZXVadUJ5VmFCSkpxRFFRX1E&pli=1#gid=0",
	"doc stopletter": "https://docs.google.com/document/d/1ButYaAkZOnlusv0p9Sn_eZqZ51g68V0HUEbFhf5znUQ/edit",
	"doc blog dev": "https://docs.google.com/document/d/1QpvBeYqs9qoCK7J7ntbvG9YyIBsAUhfcMGOu62NqZRc/edit",
	"vip dash": "https://lobby.vip.wordpress.com/",
	"SBox": "",
	"justen": "http://justen.devwp.time.com",
	"admin": "http://justen.devwp.time.com/wp-admin",
	"olympics dev": "http://olympics.justen.devwp.time.com/",
	"oly admin": "http://olympics.justen.devwp.time.com/wp-admin/",
	"GIT": "",
	"time-scripts": "https://github.com/timecom/time-scripts",
	"timethemoment": "https://github.com/timecom/timethemoment",
	"timelife": "https://github.com/timecom/timelife",
	"time2012": "https://github.com/timecom/time2012",
	"timebasic": "https://github.com/timecom/timebasic3",
	"time-plugins": "https://github.com/timecom/timecom-plugins",
	"time-mobile": "https://github.com/timecom/time-mobile",
	"redesign": "https://github.com/timecom/client-time-redesign",
	"OLY": "",
	"design stage": "http://timestaging.com/2012/web/olympics/v02/olympics_home.html",
	"mail": "",
	"gmail": "https://mail.google.com/mail/u/0/?shva=1#label/time"
	}
}
