{ "links" : {
	"NEWS": "",
	"tnr": "http://tnr.com",
	"digg": "http://digg.com/",
	"longform": "http://longform.org/",
	"upworthy": "http://upworthy.com",
	"readability": "http://www.readability.com/top-reads/",
	"rt.ly": "http://rt.ly/#d=tnr.com",

	"RESOURCE": "",
	"google videos": "http://www.youtube.com/user/GoogleWebmasterHelp",
	"reader": "http://www.google.com/reader/view/#stream/user%2F18305779273755753157%2Flabel%2FNew%20Feeds",
	"newsdiffs": "http://www.newsdiffs.org/press/",
	"netmarket": "http://www.netmarketshare.com/",
	
	"TOOLS": "",
	"utm": "http://support.google.com/analytics/bin/answer.py?hl=en&answer=1033867",
	"gcal": "http://support.google.com/calendar/bin/answer.py?hl=en&answer=1186917",
	"digg sumbit": "http://digg.com/submit",
	"bit.ly": "http://bit.ly",
	"chartbeat": "http://chartbeat.com/",
	"analytics": "http://www.google.com/analytics/",
	"parsely": "https://dash.parsely.com/tnr.com/",
	"google tools": "https://www.google.com/webmasters/tools/home?hl=en",
	"vimeo": "https://vimeo.com/settings/upgrade",
	"ga url builder": "http://support.google.com/analytics/bin/answer.py?hl=en&answer=1033867",
	
	"SOCIAL": "",
	"fb": "https://www.facebook.com/thenewrepublic",
	"twitter": "https://twitter.com/tnr",
	"gplus": "https://plus.google.com/+thenewrepublic/",
		
	"ADMIN": "",
	"esp": "https://www.pubservice.com/login.aspx",
	"hubspot": "https://app.hubspot.com/contacts/248084/",
	"itunes": "https://itunesconnect.apple.com/",
	"sprout": "https://sproutsocial.com/",
	"liveball": "https://tnr.postclickmarketing.com/Admin/Login.aspx",
	"nook": "https://partnerreporting.barnesandnoble.com/dashboard/",
	"kindle": "https://kindlepublishing.amazon.com/gp/vendor/sign-in/176-8472669-6327349",
	"play": "https://www.google.com/producer/feature/enable?feature=magazines,repub,ofip",
	"cafepress": "http://members.cafepress.com/stores/customize_prem.aspx",
	"mailchimp": "https://us1.admin.mailchimp.com/",
	"jjomedia": "https://jjomedia.basecamphq.com/",
	"optimizely": "https://www.optimizely.com/dashboard",
	"wufoo": "https://secure.wufoo.com/login/",
	"redmine": "https://work.alley.ws/projects/tnr/issues?sort=updated_on%3Adesc%2Cid%3Adesc",
	"nac": "https://www.nac.net/customercare.asp",
	"webnames": "https://www.webnames.ca/",
	"sub page": "https://www.pubservice.com/tnr/Subnew.aspx?pk=M2CHTPA",
	"admin": "http://www.tnr.com/user/login",
	"home promo": "http://www.tnr.com/admin/build/block/configure/custom_blocks/homepage_promo",
	"content overlay": "http://www.tnr.com/admin/settings/content_overlay",
	"old tnr site": "http://tnr.alley.ws/",
	"tnr.com": "http://tnr.com"
	}
}
